// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesRentalEF.Data;

namespace MoviesRentalEF.Migrations
{
    [DbContext(typeof(MoviesRentalEFContext))]
    [Migration("20210303210526_Customers")]
    partial class Customers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesRentalEF.Model.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Copies")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RentalCost")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("MovieID");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.RentedMovies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerID1")
                        .HasColumnType("int");

                    b.Property<int>("CustomerRefId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MovieID1")
                        .HasColumnType("int");

                    b.Property<int>("MovieRefId")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int?>("RentedMoviesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID1");

                    b.HasIndex("MovieID1");

                    b.HasIndex("RentedMoviesID");

                    b.ToTable("RentedMovies");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.RentedMovies", b =>
                {
                    b.HasOne("MoviesRentalEF.Model.Customer", "CustomerID")
                        .WithMany("RentedMovies")
                        .HasForeignKey("CustomerID1");

                    b.HasOne("MoviesRentalEF.Model.Movie", "MovieID")
                        .WithMany("RentedMovies")
                        .HasForeignKey("MovieID1");

                    b.HasOne("MoviesRentalEF.Model.RentedMovies", null)
                        .WithMany("RentedMovie")
                        .HasForeignKey("RentedMoviesID");

                    b.Navigation("CustomerID");

                    b.Navigation("MovieID");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.Customer", b =>
                {
                    b.Navigation("RentedMovies");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.Movie", b =>
                {
                    b.Navigation("RentedMovies");
                });

            modelBuilder.Entity("MoviesRentalEF.Model.RentedMovies", b =>
                {
                    b.Navigation("RentedMovie");
                });
#pragma warning restore 612, 618
        }
    }
}
